# Generated by Django 5.2.4 on 2025-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_url', models.CharField(max_length=100)),
                ('whatsapp_url', models.CharField(max_length=100)),
                ('telegram_url', models.CharField(max_length=100)),
            ],
        ),
    ]
